name: Build Node.js Application

# Este workflow se ejecutará cada vez que haya un push en las ramas especificadas
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    # Define en qué sistema operativo se ejecutará la acción
    runs-on: ubuntu-latest

    # Pasos a seguir en el job
    steps:
      # Este paso usa la acción de GitHub para obtener el código de tu repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Este paso configura Node.js en el runner de GitHub
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Puedes cambiar esta versión según tu proyecto

      # Este paso instala las dependencias usando npm
      - name: Install dependencies
        working-directory: ./front-end
        run: npm install

      # Este paso ejecuta el script para generar el build de producción
      - name: Build production version
        working-directory: ./front-end
        run: npm run build

      # Este paso sube el build generado a GitHub Actions
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: front-end/dist

      # Este paso hace commit y push del build generado
      - name: Configure Git
        run: |
          git config --global user.name "UnaiHerna"
          git config --global user.email "unaixiba@gmail.com"
          git add .
          git commit -m "Add production build" || echo "No changes to commit"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push origin main